/* Truck Test 2.0 · gerador da apresentação (HTML autônomo, 1280×720 por página, sistema visual Tecar). */
'use strict';
const TTREPORT = (() => {
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
const nl = s => esc(s).replace(/\n/g, '<br>');
const isN = v => typeof v === 'number' && isFinite(v);
const n0 = v => isN(v) ? Math.round(v).toLocaleString('pt-BR') : '—';
const n1 = (v, d = 1) => isN(v) ? v.toLocaleString('pt-BR', { minimumFractionDigits: d, maximumFractionDigits: d }) : '—';
const rs = v => isN(v) ? 'R$ ' + n0(v) : '—';
const rs2 = v => isN(v) ? 'R$ ' + n1(v, 2) : '—';
const pc = (v, d = 1) => isN(v) ? n1(v * 100, d) + '%' : '—';
const dbr = s => s ? s.slice(8, 10) + '/' + s.slice(5, 7) + '/' + s.slice(0, 4) : '—';
const GAP = (t = 'dado necessário') => `<span class="gap">${esc(t)}</span>`;
const or = (v, t) => (v === '' || v == null || (typeof v === 'number' && !isFinite(v))) ? GAP(t) : esc(v);
const EV = { med: 'Medido', cli: 'Cliente', cal: 'Cálculo', proj: 'Projeção', hip: 'Hipótese', bm: 'Benchmark' };
const ev = k => `<span class="ev ${k}">${EV[k]}</span>`;
const CSS = `*{margin:0;padding:0;box-sizing:border-box}
:root{--ink:#0d0f12;--ink2:#3c4450;--ink3:#79828f;--line:#dfe3e8;--soft:#f2f4f6;--paper:#fff;--mb:#111318;--acc:#B8432F;--teal:#00A19B;--good:#1e7b4f;--bad:#b3261e;--warn:#b7791f;--info:#3B6EA5;--out:#9AA3AD;--daf:#C9A227}
body{font-family:Inter,'Segoe UI',system-ui,sans-serif;color:var(--ink);background:#8a8f96;-webkit-font-smoothing:antialiased;font-variant-numeric:tabular-nums}
.pg{width:1280px;height:720px;background:var(--paper);position:relative;overflow:hidden;margin:0 auto 18px;display:flex;flex-direction:column}
@page{size:1280px 720px;margin:0}@media print{body{background:none}.pg{margin:0;page-break-after:always}.pg:last-child{page-break-after:auto}}
.hd{display:flex;align-items:flex-end;gap:14px;padding:26px 46px 12px;border-bottom:2px solid var(--mb)}
.hd .n{font-size:34px;font-weight:800;color:var(--line);line-height:.85;letter-spacing:-.03em}.hd .t{flex:1;min-width:0}
.hd h2{font-size:20px;font-weight:750;letter-spacing:-.01em;line-height:1.15;text-wrap:balance}.hd .s{font-size:11.5px;color:var(--ink3);margin-top:3px;font-weight:500}
.hd .tag{font-size:9px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:var(--paper);background:var(--mb);padding:4px 9px;border-radius:3px;white-space:nowrap}
.hd .tag.a{background:var(--acc)}.hd .tag.w{background:var(--warn)}
.bd{flex:1;padding:16px 46px 14px;display:flex;flex-direction:column;gap:11px;min-height:0}.bd>.g,.bd>.stmt,.bd>.photos{flex:1;min-height:0}.bd>.g>.pn{min-height:0}.bd>.g>div{min-height:0}
.ft{padding:7px 46px 12px;border-top:1px solid var(--line);display:flex;justify-content:space-between;gap:20px;font-size:8.5px;color:var(--ink3);letter-spacing:.05em;text-transform:uppercase;font-weight:600}
.kpis{display:grid;gap:10px}.k4{grid-template-columns:repeat(4,1fr)}.k5{grid-template-columns:repeat(5,1fr)}.k3{grid-template-columns:repeat(3,1fr)}
.kp{border:1px solid var(--line);border-left:3px solid var(--mb);border-radius:6px;padding:9px 12px;min-width:0}
.kp .l{font-size:9px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;color:var(--ink3)}.kp .v{font-size:24px;font-weight:800;letter-spacing:-.02em;line-height:1.1;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.kp .v small{font-size:12px;font-weight:600;color:var(--ink3);letter-spacing:0}.kp .d{font-size:10px;color:var(--ink2);margin-top:3px;line-height:1.35}
.kp.a{border-left-color:var(--acc)}.kp.g{border-left-color:var(--good)}.kp.w{border-left-color:var(--warn)}.kp.t{border-left-color:var(--teal)}.kp.b{border-left-color:var(--info)}
.g{display:grid;gap:11px;min-height:0}.g2{grid-template-columns:1fr 1fr}.g21{grid-template-columns:2fr 1fr}.g12{grid-template-columns:1fr 2fr}.g3{grid-template-columns:1fr 1fr 1fr}
.pn{border:1px solid var(--line);border-radius:7px;padding:11px 13px;min-width:0;display:flex;flex-direction:column;background:var(--paper);overflow:hidden}
.pn h3{font-size:10.5px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;color:var(--ink);margin-bottom:7px;display:flex;justify-content:space-between;gap:10px}
.pn h3 em{font-style:normal;font-weight:500;letter-spacing:0;text-transform:none;color:var(--ink3);font-size:9.5px;text-align:right}
.pn .note{font-size:9.5px;color:var(--ink3);line-height:1.4;margin-top:auto;padding-top:6px}
table{border-collapse:collapse;width:100%;font-size:10.5px}th{font-size:8.5px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;color:var(--ink3);text-align:right;padding:4px 6px;border-bottom:1px solid var(--line)}
td{padding:4px 6px;border-bottom:1px solid var(--soft);text-align:right;color:var(--ink2)}th.l,td.l{text-align:left}td.b{font-weight:700;color:var(--ink)}td.dim{color:var(--ink3)}td.pos{color:var(--good);font-weight:700}td.neg{color:var(--bad);font-weight:700}td.warn{color:var(--warn);font-weight:700}
tr.hi td{background:var(--soft)}tr.tot td{border-top:2px solid var(--mb);font-weight:800;color:var(--ink)}
.co{background:var(--soft);border-left:3px solid var(--mb);border-radius:0 6px 6px 0;padding:8px 11px;font-size:11px;line-height:1.45;color:var(--ink2)}.co b{color:var(--ink)}
.co .t{display:block;font-size:9px;font-weight:800;letter-spacing:.1em;text-transform:uppercase;color:var(--ink3);margin-bottom:2px}
.co.g{border-left-color:var(--good)}.co.w{border-left-color:var(--warn)}.co.b{border-left-color:var(--bad)}.co.a{border-left-color:var(--acc)}.co.i{border-left-color:var(--info)}
.ev{display:inline-block;font-size:8px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;padding:1px 5px;border-radius:3px;border:1px solid;vertical-align:middle;margin-left:4px}
.ev.med{color:var(--teal);border-color:var(--teal)}.ev.cli{color:var(--info);border-color:var(--info)}.ev.cal{color:var(--ink2);border-color:var(--ink2)}.ev.proj{color:var(--warn);border-color:var(--warn)}.ev.hip{color:var(--bad);border-color:var(--bad)}.ev.bm{color:var(--daf);border-color:var(--daf)}
.gap{display:inline-block;font-size:9px;font-weight:700;color:var(--bad);border:1px dashed var(--bad);border-radius:3px;padding:1px 5px;text-transform:uppercase;letter-spacing:.04em;white-space:nowrap}
.chip{display:inline-block;font-size:8.5px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;padding:2px 6px;border-radius:3px;border:1px solid var(--line);color:var(--ink2)}.chip.g{color:var(--good);border-color:var(--good)}.chip.w{color:var(--warn);border-color:var(--warn)}.chip.b{color:var(--bad);border-color:var(--bad)}
.dl{display:grid;grid-template-columns:auto 1fr;gap:3px 12px;font-size:11px}.dl dt{color:var(--ink3);font-weight:600}.dl dd{color:var(--ink);font-weight:600}
svg text{font-family:Inter,system-ui,sans-serif}
.cover{background:var(--mb);color:#fff;justify-content:flex-end}.cover .ph{position:absolute;inset:0;background-size:cover;background-position:center;opacity:.55}
.cover .ov{position:absolute;inset:0;background:linear-gradient(180deg,rgba(17,19,24,.1) 0%,rgba(17,19,24,.85) 70%)}
.cover .in{position:relative;padding:0 64px 54px;display:flex;flex-direction:column;gap:12px}.cover .eb{font-size:11px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:#c9ced6}
.cover h1{font-size:44px;font-weight:800;letter-spacing:-.02em;line-height:1.05;max-width:900px;text-wrap:balance}.cover .sub{font-size:16px;color:#dfe3e8;font-weight:500;max-width:900px}
.cover .logos{position:absolute;top:40px;left:64px;right:64px;display:flex;justify-content:space-between;align-items:center}.cover .logos img{max-height:64px;max-width:240px;background:#fff;padding:8px 12px;border-radius:6px}
.cover .tecar{font-size:12px;font-weight:800;letter-spacing:.16em;text-transform:uppercase;color:#fff;border:1.5px solid #fff;padding:8px 12px;border-radius:4px}
.photos{display:grid;gap:8px;grid-template-columns:repeat(3,1fr)}.photos figure{border:1px solid var(--line);border-radius:6px;overflow:hidden;background:var(--soft)}.photos img{width:100%;height:150px;object-fit:cover;display:block}.photos figcaption{font-size:9.5px;padding:5px 7px;color:var(--ink2)}
.big{font-size:56px;font-weight:800;letter-spacing:-.03em;line-height:1;color:var(--acc)}.big small{font-size:16px;color:var(--ink3);font-weight:600;letter-spacing:0}
.tl{display:flex;align-items:center;gap:0;margin:6px 0}.tl .st{flex:1;text-align:center;font-size:10px;color:var(--ink2);position:relative;padding-top:14px}.tl .st:before{content:'';position:absolute;top:0;left:0;right:0;height:3px;background:var(--line)}.tl .st.on:before{background:var(--mb)}.tl .st b{display:block;font-size:12px;color:var(--ink)}
.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.steps .s{border:1px solid var(--line);border-radius:6px;padding:10px 12px}.steps .s b{display:block;font-size:12px}.steps .s span{font-size:10.5px;color:var(--ink2)}
.stmt{font-size:26px;font-weight:750;line-height:1.25;letter-spacing:-.01em;text-wrap:balance;max-width:1000px}`;
/* ---------- SVG helpers ---------- */
const hbars = (rows, { w = 560, h = 180, fmt = v => n1(v, 2), max } = {}) => {
 const L = 150, R = 80, bh = Math.min(22, (h - 10) / rows.length - 6), mx = max || Math.max(1e-9, ...rows.map(r => Math.abs(r.v)));
 return `<svg viewBox="0 0 ${w} ${h}" width="100%" height="${h}">` + rows.map((r, i) => { const y = 6 + i * ((h - 10) / rows.length), bw = Math.max(0, Math.abs(r.v) / mx * (w - L - R)); return `<text x="${L - 8}" y="${y + bh / 2 + 3.5}" text-anchor="end" font-size="9.5" font-weight="650" fill="#3c4450">${esc(r.l)}</text><rect x="${L}" y="${y}" width="${bw}" height="${bh}" rx="2" fill="${r.c || '#111318'}"/><text x="${L + bw + 6}" y="${y + bh / 2 + 3.5}" font-size="9.5" font-weight="700" fill="#3c4450">${esc(fmt(r.v))}</text>`; }).join('') + '</svg>';
};
const diverge = (rows, { w = 560, h = 200, fmt = v => rs(v) } = {}) => {
 const L = 150, R = 70, mid = L + (w - L - R) / 2, mx = Math.max(1e-9, ...rows.map(r => Math.abs(r.v))), sc = (w - L - R) / 2 / mx, bh = Math.min(20, (h - 10) / rows.length - 6);
 return `<svg viewBox="0 0 ${w} ${h}" width="100%" height="${h}"><line x1="${mid}" y1="4" x2="${mid}" y2="${h - 4}" stroke="#dfe3e8"/>` + rows.map((r, i) => { const y = 6 + i * ((h - 10) / rows.length), bw = Math.abs(r.v) * sc, x = r.v >= 0 ? mid : mid - bw; return `<text x="${L - 8}" y="${y + bh / 2 + 3.5}" text-anchor="end" font-size="9.5" font-weight="650" fill="#3c4450">${esc(r.l)}</text><rect x="${x}" y="${y}" width="${bw}" height="${bh}" rx="2" fill="${r.v >= 0 ? '#1e7b4f' : '#b3261e'}"/><text x="${r.v >= 0 ? mid + bw + 6 : (bw > 70 ? mid - 6 : mid - bw - 6)}" y="${y + bh / 2 + 3.5}" text-anchor="${r.v >= 0 ? 'start' : 'end'}" font-size="9" font-weight="700" fill="${r.v < 0 && bw > 70 ? '#fff' : '#3c4450'}">${(r.v >= 0 ? '+' : '−') + esc(fmt(Math.abs(r.v)))}</text>`; }).join('') + '</svg>';
};
const vbars = (groups, series, { w = 560, h = 190, fmt = v => n1(v, 2), colors = ['#111318', '#9AA3AD'] } = {}) => {
 const L = 36, B = 26, T = 18, mx = Math.max(1e-9, ...groups.flatMap(g => g.v).filter(v => isFinite(v))) * 1.15, gw = (w - L - 10) / groups.length, bw = Math.min(46, gw / (series.length + 1));
 let s = `<svg viewBox="0 0 ${w} ${h}" width="100%" height="${h}">`;
 [0, .5, 1].forEach(f => { const y = T + (1 - f) * (h - T - B); s += `<line x1="${L}" y1="${y}" x2="${w - 10}" y2="${y}" stroke="#f2f4f6"/>`; });
 groups.forEach((g, i) => { const x0 = L + i * gw + (gw - bw * series.length) / 2; g.v.forEach((v, j) => { const bh = isFinite(v) ? v / mx * (h - T - B) : 0, x = x0 + j * bw, y = T + (h - T - B) - bh; s += `<rect x="${x + 2}" y="${y}" width="${bw - 4}" height="${bh}" rx="2" fill="${colors[j]}"/><text x="${x + bw / 2}" y="${y - 4}" text-anchor="middle" font-size="9.5" font-weight="700" fill="#3c4450">${isFinite(v) ? esc(fmt(v)) : '—'}</text>`; }); s += `<text x="${L + i * gw + gw / 2}" y="${h - 8}" text-anchor="middle" font-size="9.5" font-weight="650" fill="#3c4450">${esc(g.l)}</text>`; });
 s += series.map((n, j) => `<rect x="${L + j * 120}" y="2" width="9" height="9" rx="2" fill="${colors[j]}"/><text x="${L + j * 120 + 13}" y="10" font-size="9" font-weight="600" fill="#3c4450">${esc(n)}</text>`).join('');
 return s + '</svg>';
};
const lines = (arrs, { w = 560, h = 200, names = [], colors = ['#111318', '#9AA3AD'], mark } = {}) => {
 const L = 60, B = 24, T = 16, H = arrs[0].length - 1, mx = Math.max(1e-9, ...arrs.flat()), X = i => L + i / H * (w - L - 12), Y = v => T + (1 - v / mx) * (h - T - B);
 let s = `<svg viewBox="0 0 ${w} ${h}" width="100%" height="${h}">`;
 [0, .25, .5, .75, 1].forEach(f => { const y = Y(mx * f); s += `<line x1="${L}" y1="${y}" x2="${w - 12}" y2="${y}" stroke="#f2f4f6"/><text x="${L - 6}" y="${y + 3}" text-anchor="end" font-size="8.5" fill="#79828f">${Math.round(mx * f / 1000).toLocaleString('pt-BR')} mil</text>`; });
 [0, .25, .5, .75, 1].forEach(f => { const i = Math.round(H * f); s += `<text x="${X(i)}" y="${h - 8}" text-anchor="middle" font-size="8.5" fill="#79828f">mês ${i}</text>`; });
 arrs.forEach((a, j) => { s += `<path d="${a.map((v, i) => (i ? 'L' : 'M') + X(i).toFixed(1) + ' ' + Y(v).toFixed(1)).join(' ')}" fill="none" stroke="${colors[j]}" stroke-width="2.5"/><rect x="${L + j * 150}" y="2" width="9" height="9" rx="2" fill="${colors[j]}"/><text x="${L + j * 150 + 13}" y="10" font-size="9" font-weight="600" fill="#3c4450">${esc(names[j] || '')}</text>`; });
 if (mark) s += `<line x1="${X(mark)}" y1="${T}" x2="${X(mark)}" y2="${h - B}" stroke="#B8432F" stroke-dasharray="4 3"/><text x="${X(mark) + 4}" y="${T + 12}" font-size="9" font-weight="800" fill="#B8432F">payback · mês ${mark}</text>`;
 return s + '</svg>';
};
const radar = (rows, { size = 230 } = {}) => {
 const cx = size / 2 + 40, cy = size / 2 + 6, r = size / 2 - 22, n = rows.length, ang = i => -Math.PI / 2 + i * 2 * Math.PI / n;
 const pt = (i, v) => [cx + Math.cos(ang(i)) * r * v / 5, cy + Math.sin(ang(i)) * r * v / 5];
 let s = `<svg viewBox="0 0 ${size + 80} ${size + 12}" width="100%" height="${size + 12}">`;
 [1, 2, 3, 4, 5].forEach(k => { s += `<polygon points="${rows.map((_, i) => pt(i, k).join(',')).join(' ')}" fill="none" stroke="${k === 5 ? '#dfe3e8' : '#f2f4f6'}"/>`; });
 rows.forEach((row, i) => { const [x, y] = pt(i, 5.9); s += `<text x="${x}" y="${y + 3}" text-anchor="middle" font-size="8.5" font-weight="600" fill="#3c4450">${esc(row.l)}</text>`; });
 const poly = (key, col, fill) => `<polygon points="${rows.map((row, i) => pt(i, row[key] || 0).join(',')).join(' ')}" fill="${fill}" stroke="${col}" stroke-width="2"/>`;
 s += poly('atual', '#9AA3AD', 'rgba(154,163,173,.18)') + poly('mb', '#111318', 'rgba(17,19,24,.12)');
 return s + '</svg>';
};
const stack = (parts, { w = 560, h = 48, fmt = v => rs2(v) } = {}) => {
 const tot = parts.reduce((s, p) => s + Math.max(0, p.v), 0) || 1; let x = 0, s = `<svg viewBox="0 0 ${w} ${h}" width="100%" height="${h}">`;
 parts.forEach(p => { const bw = Math.max(0, p.v) / tot * w; if (bw > 0) { s += `<rect x="${x}" y="8" width="${bw}" height="22" fill="${p.c}"/>`; if (bw > 40) s += `<text x="${x + bw / 2}" y="23" text-anchor="middle" font-size="9" font-weight="700" fill="#fff">${Math.round(p.v / tot * 100)}%</text>`; s += `<text x="${x + 1}" y="42" font-size="8.5" fill="#3c4450">${esc(p.l)} ${esc(fmt(p.v))}</text>`; x += bw; } });
 return s + '</svg>';
};
/* ---------- páginas ---------- */
function build(T, R) {
 const hoje = new Date().toLocaleDateString('pt-BR'), emp = T.cli.empresa || 'Cliente', P = [];
 const fotoTipo = t => T.fotos.filter(f => f.tipo === t);
 const capa = fotoTipo('capa')[0] || T.fotos.find(f => f.tipo !== 'mapa' && f.tipo !== 'logo');
 const page = (...args) => { let [num, title, sub, tag, body, foot, cls = ''] = args; if (body === 'a' || body === 'w') { cls = body; body = foot; foot = args[6] || ''; } title = title.charAt(0).toUpperCase() + title.slice(1); P.push(`<section class="pg"><div class="hd"><div class="n">${String(num).padStart(2, '0')}</div><div class="t"><h2>${title}</h2><div class="s">${sub}</div></div><div class="tag ${cls}">${tag}</div></div><div class="bd">${body}</div><div class="ft"><span>${foot}</span><span>${esc(emp)} · Truck Test 2.0 · Tecar Caminhões · ${hoje}</span></div></section>`); };
 const kp = (l, v, d, c = '') => `<div class="kp ${c}"><div class="l">${l}</div><div class="v">${v}</div><div class="d">${d}</div></div>`;
 const pn = (t, b, em = '') => `<div class="pn"><h3>${t}${em ? `<em>${em}</em>` : ''}</h3>${b}</div>`;
 const co = (t, b, c = '') => `<div class="co ${c}"><span class="t">${t}</span>${b}</div>`;
 const rota = T.op.rotas ? T.op.rotas.split('\n')[0] : '';
 const cons = R.cen && R.cen.conservador, real = R.tco;
 const pbTxt = c => c.payback ? 'mês ' + c.payback : (c.rm.tco < c.rc.tco ? 'imediato' : 'não ocorre no horizonte');
 const econTxt = v => (v >= 0 ? 'economia de ' : 'custo adicional de ') + rs(Math.abs(v));
 const econL = v => v >= 0 ? 'Economia anual por caminhão' : 'Custo adicional anual por caminhão';
 // 01 capa
 P.push(`<section class="pg cover">${capa ? `<div class="ph" style="background-image:url('${capa.src}')"></div>` : ''}<div class="ov"></div><div class="logos">${T.cli.logo ? `<img src="${T.cli.logo}" alt="${esc(emp)}">` : `<span class="tecar">${esc(emp)}</span>`}<span class="tecar">Tecar · Mercedes-Benz</span></div><div class="in"><div class="eb">Truck Test 2.0 · validação técnica e econômica da operação</div><h1>${esc(emp)}: auditamos a operação, testamos o ${or(T.vt.modelo, 'modelo testado')} e medimos o impacto</h1><div class="sub">${esc(rota || 'Rota do teste')} · ${T.prot.inicio ? dbr(T.prot.inicio) + ' a ' + dbr(T.prot.fim) : GAP('período')} · ${R.kmTrechos || R.kmBomba ? n0(R.kmTrechos || R.kmBomba) + ' km medidos' : GAP('km medidos')}${T.prot.motorista ? ' · motorista ' + esc(T.prot.motorista) : ''}</div></div></section>`);
 // 02 resumo
 const econAnoC = cons ? R.econAno.conservador : NaN;
 page(2, R.l100Menos > 0 ? `Na sua operação, o ${esc(T.vt.modelo)} usou ${n1(R.l100Menos)} litros a menos por 100 km no mix real${cons ? `: ${econTxt(econAnoC)} por caminhão por ano` : ''}` : (isN(R.l100Menos) ? `No mix real da operação, o ${esc(T.vt.modelo)} consumiu ${n1(-R.l100Menos)} litros a mais por 100 km que a média da frota` : `Resumo executivo: o que o teste mediu e o que ainda falta para fechar a decisão`),
  'A resposta em uma página; as provas vêm nas seguintes', 'Executive summary', `<div class="kpis k4">
  ${kp(R.l100Menos >= 0 ? 'Litros a menos por 100 km' : 'Litros a mais por 100 km', isN(R.l100Menos) ? `${n1(Math.abs(R.l100Menos))}<small> L</small>` : GAP(), `mix real · ${n1(R.kmlMB, 2)} × ${n1(R.kml0, 2)} km/L · carregado ${n1(R.car.kml, 2)} ${ev('med')}${ev('cli')}`, 'a')}
  ${kp('Custo operacional por km', isN(R.opexDelta) ? `${R.opexDelta >= 0 ? '−' : '+'}${rs2(Math.abs(R.opexDelta))}` : GAP(), `combustível + ARLA + manutenção + pneus + parada ${ev('cal')}`, 't')}
  ${kp(cons ? econL(econAnoC) : 'Economia anual por caminhão', cons ? rs(Math.abs(econAnoC)) : GAP('TCO'), `cenário conservador · TCO em ${real ? real.rm.H : 60} meses ${ev('proj')}`, 'g')}
  ${kp('Payback', cons ? pbTxt(cons) : GAP('TCO'), cons ? `curva acumulada MB abaixo da atual a partir daí ${ev('cal')}` : 'depende do TCO', 'b')}</div>
  <div class="g g2"><div class="pn"><h3>O que o teste comprovou</h3><div class="dl"><dt>Veículo</dt><dd>${or(T.vt.modelo)} · ${or(T.vt.placa, 'placa')}</dd><dt>Período</dt><dd>${R.dias ? R.dias + ' dias' : GAP()} · ${n0(R.kmTrechos || R.kmBomba)} km · ${R.nAbast} abastecimentos</dd><dt>Consumo</dt><dd>${n1(R.kmlMB, 2)} km/L ponderado (${esc(R.fonteKml || '—')})</dd><dt>Aderência à operação</dt><dd>${isN(R.aderencia) ? pc(R.aderencia, 0) : GAP('RDI')}</dd><dt>Testado × ofertado</dt><dd>${R.compatId} idênticos · ${R.compatEq} equivalentes · ${R.compatDif.length} diferentes · ${R.compatPend} pendentes</dd><dt>Motorista</dt><dd>${R.drvN ? `${n1(R.drvMB)} × ${n1(R.drvAtual)} (0–5)` : GAP('scorecard')}</dd></div></div>
  ${pn('Decisão proposta', `<div class="co a">${T.prop.decisao ? nl(T.prop.decisao) : GAP('decisão proposta')}</div><div class="co" style="margin-top:8px"><span class="t">Base da conclusão</span>Números medidos no teste, dados da frota informados por ${esc(emp)} e TCO no cenário conservador. Projeções estão marcadas como tal.</div>`)}</div>`,
  'Resumo · cada número carrega sua classe de evidência');
 // 03 operação
 page(3, `${esc(emp)} roda ${or(T.op.kmMes, 'km/mês')} km/mês com ${or(T.cli.frotaTotal, 'frota')} caminhões em ${esc(T.op.aplicacao || 'aplicação')}, levando ${or(T.op.cargaMedia, 'carga')} t`, 'Como o cliente ganha dinheiro hoje', 'Ato 1 · Operação', `<div class="kpis k5">
  ${kp('Frota', `${or(T.cli.frotaTotal)}<small> un</small>`, `${esc(T.cli.marcas || '')} · idade média ${or(T.cli.idadeMedia, 'anos')} anos ${ev('cli')}`)}
  ${kp('Elegíveis à renovação', `${or(T.cli.frotaElegivel)}<small> un</small>`, 'mesma aplicação, em idade de troca', 'w')}
  ${kp('Quilometragem', `${or(T.op.kmMes)}<small> km/mês</small>`, `${or(T.op.diasOper)} dias operacionais ${ev('cli')}`)}
  ${kp('Carga', `${or(T.op.cargaMedia)}<small> t média</small>`, `máx. ${or(T.op.cargaMax)} t · ${esc(T.op.implemento || '')}`)}
  ${kp('Mix carregado / vazio', `${or(T.op.mixCarregado)}%<small> carregado</small>`, `${or(T.op.entregasDia, 'n')} entregas ou viagens por dia`)}</div>
  <div class="g g21">${pn('Rotas e perfil da operação', `<div class="dl"><dt>Segmento</dt><dd>${or(T.cli.segmento)} · ${esc(T.cli.atividade || '')}</dd><dt>Rotas</dt><dd>${T.op.rotas ? nl(T.op.rotas) : GAP()}</dd><dt>Perfil</dt><dd>${or(T.op.perfilRod, '% rodoviário')}% rodoviário · ${or(T.op.velMedia, 'km/h')} km/h médios · ${or(T.op.paradas100, 'n')} paradas/100 km · ${or(T.op.ganhoAlt, 'm')} m de ganho de altitude/100 km</dd><dt>Jornada</dt><dd>${or(T.op.jornada)}</dd><dt>Sazonalidade</dt><dd>${or(T.op.sazonalidade)}</dd></div>`)}
  ${pn('Principais dores declaradas', `<div class="co i">${T.cli.dores ? nl(T.cli.dores) : GAP('dores do cliente')}</div><p class="note">Informado por ${esc(T.cli.contato || 'contato')}${T.cli.cargo ? ', ' + esc(T.cli.cargo) : ''} no formulário pré-teste. ${ev('cli')}</p>`)}</div>`,
  'Formulário pré-teste · base de emplacamentos Tecar');
 // 04 baseline
 const oa = R.opexAtual;
 page(4, oa ? `Combustível é ${pc(R.opexShareComb, 0)} do custo operacional por km da frota atual; cada 0,1 km/L vale ${rs(R.valor01kml)} por ano por caminhão` : 'Baseline da frota atual: onde está o dinheiro', 'O custo de hoje, com dado do próprio cliente', 'Ato 2 · Baseline e desafio', `<div class="kpis k4">
  ${kp('Veículo atual', or(T.base.modelo, 'modelo'), `${esc(T.base.marca || '')} · ${or(T.base.qtd, 'n')} un · ano ${or(T.base.ano)}`)}
  ${kp('Consumo da frota', isN(R.kml0) && R.kml0 > 0 ? `${n1(R.kml0, 2)}<small> km/L</small>` : GAP(), `${n1(R.l100Atual)} L/100 km · fonte: ${esc(T.base.fonteKml)} ${ev('cli')}`, 'b')}
  ${kp('Custo operacional', oa ? `${rs2(oa.total)}<small>/km</small>` : GAP(), 'combustível + ARLA + manutenção + pneus + parada', 't')}
  ${kp('Um dia parado custa', isN(R.valorDiaParado) ? rs(R.valorDiaParado) : GAP(), `${or(T.base.diasParados, 'n')} dias parados por ano por veículo ${ev('cli')}`, 'w')}</div>
  <div class="g g21">${pn('Custo operacional por km, por componente', oa ? stack([{ l: 'Combustível', v: oa.comb, c: '#111318' }, { l: 'ARLA', v: oa.ar, c: '#3B6EA5' }, { l: 'Manutenção', v: oa.ma, c: '#79828f' }, { l: 'Pneus', v: oa.pn, c: '#9AA3AD' }, { l: 'Parada', v: oa.pa, c: '#b7791f' }]) + `<table style="margin-top:8px"><thead><tr><th class="l">Componente</th><th>R$/km</th><th>R$/mês</th><th>Fonte</th></tr></thead><tbody>${[['Combustível', oa.comb, 'cli'], ['ARLA 32', oa.ar, 'cli'], ['Manutenção', oa.ma, T.base.manut ? 'cli' : 'bm'], ['Pneus', oa.pn, T.base.pneus ? 'cli' : 'bm'], ['Indisponibilidade', oa.pa, 'cal']].map(([l, v, e]) => `<tr><td class="l">${l}</td><td>${rs2(v)}</td><td>${rs(v * (TT.N(T.op.kmMes)))}</td><td>${ev(e)}</td></tr>`).join('')}<tr class="tot"><td class="l">Total</td><td>${rs2(oa.total)}</td><td>${rs(oa.total * TT.N(T.op.kmMes))}</td><td></td></tr></tbody></table>` : `<div class="co b">${GAP('consumo da frota e preço do diesel')} Sem baseline não há benchmark nem TCO comparativo.</div>`, `diesel ${rs2(TT.N(T.base.diesel))}/L · ARLA ${rs2(TT.N(T.base.arlaPreco))}/L`)}
  ${pn('Onde há oportunidade', co('Combustível', `Cada 0,1 km/L a mais vale <b>${rs(R.valor01kml)}</b> por ano por caminhão na quilometragem atual.`, 'a') + co('Disponibilidade', `Cada dia parado custa <b>${rs(R.valorDiaParado)}</b>${TT.N(T.base.diasParados) > 0 ? `; a frota declara ${esc(T.base.diasParados)} dias por ano por veículo` : ''}.`, 'w') + co('Condução e residual', 'Marcha lenta, freio de serviço e valor de revenda entram nas páginas 10 e 14.', ''))}</div>`,
  'Dado do cliente (formulário pré-teste) · cálculo Tecar');
 // 05 hipótese
 const feats = (T.features || '').split('\n').map(l => l.split('|').map(x => x.trim())).filter(l => l[0]);
 page(5, `Para ${esc(T.op.cargaMedia || '[carga]')} t em ${esc(rota || '[rota]')}, a configuração indicada é ${or(T.vo.modelo || T.vt.modelo, 'modelo')} · ${or(T.vo.motor || T.vt.motor, 'motor')} · relação ${or(T.vo.relacao || T.vt.relacao, 'relação')}`, 'Por que esse caminhão, e não outro', 'Ato 3 · Hipótese', `<div class="g g12">${pn('Configuração', `<div class="dl">${TT.COMPAT_ITEMS.map(([k, l]) => `<dt>${l}</dt><dd>${or(T.vo[k] || T.vt[k])}</dd>`).join('')}</div>`, 'ofertada; testada na página 6')}
  ${pn('Cada escolha técnica, seu efeito na operação e no dinheiro', feats.length ? `<table><thead><tr><th class="l">Característica</th><th class="l">Efeito operacional</th><th class="l">Efeito financeiro</th></tr></thead><tbody>${feats.map(f => `<tr><td class="l b">${esc(f[0])}</td><td class="l">${esc(f[1] || '')}</td><td class="l">${esc(f[2] || '')}</td></tr>`).join('')}</tbody></table>` : `<div class="co w">${GAP('características → efeito operacional → efeito financeiro')} Preencha no módulo: uma linha por item, separando com |.</div>`, 'feature → efeito operacional → efeito financeiro')}</div>`,
  'Ficha técnica Mercedes-Benz · aplicação declarada pelo cliente');
 // 06 compat
 page(6, `Testado × ofertado: ${R.compatId} de ${R.compat.length} itens idênticos, ${R.compatEq} equivalentes, ${R.compatDif.length} diferentes${R.compatPend ? `, ${R.compatPend} pendentes` : ''}`, 'O resultado vale para o caminhão que será comprado?', 'Compatibilidade', 'w', `<div class="g g21">${pn('Verificação item a item', `<table><thead><tr><th class="l">Item</th><th class="l">Testado</th><th class="l">Ofertado</th><th class="l">Status</th><th class="l">Impacto declarado</th></tr></thead><tbody>${R.compat.map(c => `<tr><td class="l b">${c.l}</td><td class="l">${esc(c.a) || GAP()}</td><td class="l">${esc(c.b) || GAP()}</td><td class="l">${{ identico: '<span class="chip g">Idêntico</span>', equivalente: '<span class="chip w">Equivalente</span>', diferente: '<span class="chip b">Diferente</span>', pendente: GAP('pendente') }[c.st]}</td><td class="l">${esc(c.nota)}</td></tr>`).join('')}</tbody></table>`)}
  ${pn('Regra', co('Nunca vender uma configuração com o resultado de outra', 'Toda diferença é declarada aqui e volta na página de riscos. Se afetar consumo, o cenário conservador desconta o efeito.', 'a') + (R.compatDif.length ? co('Diferenças desta proposta', R.compatDif.map(c => `<b>${c.l}:</b> ${esc(c.a)} → ${esc(c.b)}${c.nota ? ' · ' + esc(c.nota) : ''}`).join('<br>'), 'w') : co('Situação', R.compatPend ? 'Há itens pendentes na ficha; completar antes da proposta.' : 'Testado e ofertado são a mesma configuração.', 'g')))}</div>`,
  'Ficha do veículo testado (instrutor) × proposta comercial (vendedor)');
 // 07 protocolo
 const metodo = { bomba: 'tanque cheio a tanque cheio', fleetboard: 'telemetria Fleetboard', ambos: 'bomba e Fleetboard, reconciliados' }[T.prot.metodo] || '—';
 page(7, `${R.dias || '[n]'} dias, ${n0(R.kmTrechos || R.kmBomba)} km, ${R.nAbast} abastecimentos ${esc(metodo)}, telemetria em ${R.nTrechos} trechos`, 'Como medimos, para que o número resista a qualquer pergunta', 'Ato 4 · Protocolo', `<div class="tl">${[['Pré-teste', 'formulário e ficha técnica', true], ['Início', dbr(T.prot.inicio), !!T.prot.inicio], ['Operação', `${R.dias || '—'} dias · ${n0(R.kmTrechos || R.kmBomba)} km`, R.dias > 0], ['Fim', dbr(T.prot.fim), !!T.prot.fim], ['Pós-teste', 'scorecard, TCO e aceite', R.drvN > 0]].map(s => `<div class="st ${s[2] ? 'on' : ''}"><b>${s[0]}</b>${s[1]}</div>`).join('')}</div>
  <div class="kpis k5">${kp('Motorista', or(T.prot.motorista), `${or(T.prot.pctCliente)}% do tempo com motorista do cliente · ${100 - TT.N(T.prot.pctCliente, 90)}% instrutor`)}${kp('Consumo por bomba', R.kmlBomba > 0 ? `${n1(R.kmlBomba, 2)}<small> km/L</small>` : GAP(), `${n0(R.litrosBomba)} L em ${n0(R.kmBomba)} km ${ev('med')}`, 't')}${kp('Consumo por telemetria', R.kmlFb > 0 ? `${n1(R.kmlFb, 2)}<small> km/L</small>` : GAP(), `${R.nTrechos} trechos · ${n0(R.kmTrechos)} km ${ev('med')}`, 't')}${kp('Diferença entre métodos', isN(R.difMetodos) ? pc(R.difMetodos) : '—', 'Fleetboard vs bomba · aceitável até ±3%', Math.abs(R.difMetodos) > 0.03 ? 'w' : 'g')}${kp('Carregado', isN(R.pctCarregado) ? `${n1(R.pctCarregado, 0)}%<small> dos km</small>` : GAP(), `${n0(R.car.km + R.par.km)} km carregado/parcial · ${n0(R.vaz.km)} km vazio`)}</div>
  <div class="g g2">${pn('Condições do teste', `<div class="dl"><dt>Clima</dt><dd>${or(T.prot.clima)}</dd><dt>Tráfego</dt><dd>${or(T.prot.trafego)}</dd><dt>Pneus e pressão</dt><dd>${or(T.vt.pneus)} · ${or(T.prot.pressao, 'pressão')}</dd><dt>Implemento</dt><dd>${or(T.vt.implemento)}</dd><dt>Observações</dt><dd>${T.prot.obs ? nl(T.prot.obs) : '—'}</dd></div>`)}
  ${pn('Abastecimentos', T.abast.length ? `<table><thead><tr><th class="l">Data</th><th>Odômetro</th><th>Litros</th><th class="l">Posto</th></tr></thead><tbody>${T.abast.slice(0, 8).map(a => `<tr><td class="l">${dbr(a.data)}</td><td>${n0(TT.N(a.odometro))}</td><td>${n1(TT.N(a.litros), 1)}</td><td class="l">${esc(a.posto || '')}</td></tr>`).join('')}</tbody></table>${T.abast.length > 8 ? `<p class="note">+ ${T.abast.length - 8} no anexo</p>` : ''}` : `<div class="co b">${GAP('abastecimentos com odômetro e litros')}</div>`, 'tanque cheio a tanque cheio')}</div>`,
  'Protocolo Truck Test 2.0 · instrutor Tecar' + (T.cli.instrutor ? ' ' + esc(T.cli.instrutor) : ''));
 // 08 rota
 const mapa = fotoTipo('mapa')[0];
 page(8, isN(R.aderencia) ? `O teste reproduziu ${pc(R.aderencia, 0)} do perfil operacional: ${n0(R.kmTrechos)} km, ${n1(R.parT, 1)} paradas/100 km, ${n1(100 - R.urbT, 0)}% rodoviário, ${n0(R.altT)} m de ganho de altitude/100 km` : `A rota do teste: ${n0(R.kmTrechos)} km em ${R.nTrechos} trechos`, 'Essa rota representa a operação do cliente?', 'Ato 4 · Rota', `<div class="g g21">${pn('Rota do teste', mapa ? `<img src="${mapa.src}" style="width:100%;height:230px;object-fit:cover;border-radius:5px"><p class="note">${esc(mapa.legenda || 'trilha GPS do período')}</p>` : `<table><thead><tr><th class="l">Trecho</th><th>km</th><th>Carga (t)</th><th class="l">Cond.</th><th>km/L</th><th>km/h</th><th>Alt. (m)</th><th>Paradas</th></tr></thead><tbody>${T.trechos.slice(0, 10).map(t => `<tr><td class="l b">${esc(t.nome || (t.origem + ' → ' + t.destino))}</td><td>${n0(TT.N(t.km))}</td><td>${n1(TT.N(t.cargaT), 1)}</td><td class="l">${esc(t.cond || '')}</td><td>${n1(TT.N(t.kmlFb), 2)}</td><td>${n0(TT.N(t.velMedia))}</td><td>${n0(TT.N(t.ganhoAlt))}</td><td>${n0(TT.N(t.paradas))}</td></tr>`).join('') || `<tr><td class="l" colspan="8">${GAP('trechos')}</td></tr>`}</tbody></table>`, mapa ? 'mapa real · trechos no anexo' : 'sem mapa anexado: trilha GPS pendente')}
  ${pn('Severidade da rota (RDI)', `<div class="kpis k2" style="grid-template-columns:1fr 1fr">${kp('RDI do teste', isN(R.rdiTeste) ? n1(R.rdiTeste, 2) : GAP(), 'altitude, paradas, % urbano, velocidade', 't')}${kp('RDI da operação', isN(R.rdiOp) ? n1(R.rdiOp, 2) : GAP('perfil'), 'declarado pelo cliente', 'b')}</div>${co('Aderência', isN(R.aderencia) ? `O teste é <b>${pc(R.aderencia, 0)}</b> aderente ao perfil da operação normal. ${R.aderencia >= 0.8 ? 'Resultado transferível para a operação.' : 'Diferença de severidade a considerar no cenário conservador.'}` : 'Preencher o perfil da operação (página 3) e os trechos para calcular.', R.aderencia >= 0.8 ? 'g' : 'w')}<p class="note">RDI = 0,35·(altitude/100 km ÷ 500) + 0,25·(paradas/100 km ÷ 5) + 0,25·(% urbano) + 0,15·(50 ÷ velocidade média). ${ev('cal')}</p>`)}</div>`,
  'Trilha e trechos do Fleetboard · carga por trecho (tickets) · perfil declarado pelo cliente');
 // 09 consumo
 page(9, R.car.kml > 0 ? `O ${esc(T.vt.modelo)} fez ${n1(R.car.kml, 2)} km/L carregado e ${n1(R.vaz.kml, 2)} km/L vazio: ${n1(R.kmlPond, 2)} km/L no mix real da operação` : 'Consumo medido: por trecho e por condição de carga', 'Quanto consumiu, em que condição', 'Ato 5 · Combustível', 'a', `<div class="g g12"><div class="pn"><h3>${R.l100Menos >= 0 ? 'Litros a menos por 100 km' : 'Litros a mais por 100 km'}</h3><div class="big">${isN(R.l100Menos) ? n1(Math.abs(R.l100Menos)) : '—'}<small> L no mix real</small></div><p style="font-size:11px;color:var(--ink2);margin-top:8px">${isN(R.l100Menos) ? `${pc(R.ganhoKmlPct)} em km/L contra a média da frota · carregado: ${n1(R.car.kml, 2)} km/L (${n1(100 / R.car.kml)} L/100 km)` : GAP('baseline')}</p><p class="note">${ev('med')} consumo MB · ${ev('cli')} consumo atual · ${ev('cal')} diferença</p></div>
  ${pn('Consumo por condição · L/100 km', vbars([{ l: 'Carregado', v: [R.car.kml > 0 ? 100 / R.car.kml : NaN, R.l100Atual] }, { l: 'Vazio', v: [R.vaz.kml > 0 ? 100 / R.vaz.kml : NaN, NaN] }, { l: 'Ponderado (mix ' + TT.N(T.op.mixCarregado, 50) + '%)', v: [R.l100MB, R.l100Atual] }, { l: 'Bomba', v: [R.kmlBomba > 0 ? 100 / R.kmlBomba : NaN, NaN] }], [esc(T.vt.modelo || 'Mercedes-Benz'), esc(T.base.modelo || 'Frota atual')], { fmt: v => n1(v, 1), h: 300 }), `amplitude carregado: ${n1(R.car.min, 2)} a ${n1(R.car.max, 2)} km/L em ${R.car.n} trechos`)}</div>`,
  'Fleetboard por trecho · abastecimentos · média da frota informada pelo cliente');
 // 10 telemetria
 const te = T.tele;
 page(10, `${or(te.rpmFaixa, 'x')}% do tempo na faixa econômica, ${or(te.marchaLenta, 'y')} min de marcha lenta por dia e freio motor em ${or(te.freioMotor, 'z')}% das frenagens`, 'Por que o consumo foi esse', 'Ato 5 · Telemetria', `<div class="kpis k5">${kp('Faixa econômica', `${or(te.rpmFaixa)}%<small> do tempo</small>`, 'rotação na faixa verde', 't')}${kp('Marcha lenta', `${or(te.marchaLenta)}<small> min/dia</small>`, 'motor ligado parado', 't')}${kp('Freio motor', `${or(te.freioMotor)}%<small> das frenagens</small>`, `${or(te.frenagens100, 'n')} frenagens/100 km`, 't')}${kp('Trocas de marcha', `${or(te.trocas100)}<small> /100 km</small>`, `${or(te.cambioAuto, 'n')}% em modo automático`, 't')}${kp('Tempo em movimento', `${or(te.tempoMov)}<small> h/dia</small>`, `${or(te.velMedia, 'n')} km/h médios · carga do motor ${or(te.cargaMotor, 'n')}%`, 't')}</div>
  <div class="g g2">${pn('Leitura do instrutor', `<div class="co">${te.obs ? nl(te.obs) : GAP('leitura da telemetria')}</div>`)}${pn('O que é do caminhão e o que é condução', co('Caminhão', 'Câmbio automatizado, PPC e freio motor entregam a faixa econômica e o freio de serviço mínimo sem depender do motorista.', 'g') + co('Condução', 'Marcha lenta e frenagens bruscas são do motorista: treinamento de condução captura esse ganho em qualquer caminhão, e mais no Mercedes-Benz.', 'w') + `<p class="note">${ev('med')} indicadores · interpretação ${ev('hip')} até confirmação com a exportação completa</p>`)}</div>`,
  'Exportação Fleetboard do período');
 // 11 benchmark
 const chk = [['mesmoMotorista', 'Mesmo motorista'], ['mesmaRota', 'Mesma rota'], ['mesmaCarga', 'Mesma classe de carga'], ['mesmoPeriodo', 'Mesmo período / estação'], ['mesmoMetodo', 'Mesmo método de consumo']];
 const compNome = { 1: 'teste pareado', 2: 'histórico do mesmo percurso', 3: 'média real da frota', 4: 'concorrente equivalente' }[T.prot.comparador] || 'média da frota';
 page(11, R.equivalente ? `Contra ${esc(compNome)}: ${n1(R.kmlMB, 2)} km/L do ${esc(T.vt.modelo)} contra ${n1(R.kml0, 2)} km/L do ${esc(T.base.modelo || 'veículo atual')}` : `Comparação não equivalente: ${R.equivFalhas} condições diferem; a diferença entra só no cenário realista`, 'A comparação é justa?', 'Ato 6 · Benchmark', `<div class="g g2">${pn('Mercedes-Benz × frota atual · km/L', vbars([{ l: 'Carregado', v: [R.car.kml, R.kml0] }, { l: 'Ponderado', v: [R.kmlPond, R.kml0] }, { l: 'Bomba', v: [R.kmlBomba, R.kml0] }], [esc(T.vt.modelo || 'Mercedes-Benz'), esc(T.base.modelo || 'Frota atual')], { fmt: v => n1(v, 2), h: 300 }), `comparador: ${esc(compNome)} (nível ${esc(T.prot.comparador || '3')} de 4)`)}
  ${pn('Condições de equivalência', `<table><thead><tr><th class="l">Condição</th><th class="l">Status</th></tr></thead><tbody>${chk.map(([k, l]) => `<tr><td class="l">${l}</td><td class="l">${T.prot[k] ? '<span class="chip g">Equivalente</span>' : '<span class="chip b">Diferente / não verificado</span>'}</td></tr>`).join('')}</tbody></table>` + co('Regra de reporte', R.equivalente ? `${R.equivOk} de 5 condições equivalentes: a diferença de consumo entra no TCO nos três cenários.` : `Duas ou mais condições diferem: a diferença entra só no cenário realista; o conservador usa a melhor média do cliente.`, R.equivalente ? 'g' : 'w'))}</div>`,
  'Hierarquia de comparadores: 1 pareado · 2 histórico do percurso · 3 média da frota · 4 concorrente');
 // 12 driver
 page(12, R.drvN ? `O motorista avaliou o ${esc(T.vt.modelo)} ${n1(R.drvMB - R.drvAtual)} pontos acima do atual${R.drvMaior.length ? `, com maior diferença em ${R.drvMaior.map(r => r.l.toLowerCase()).join(' e ')}` : ''}` : 'Driver Scorecard: percepção do motorista, medida', 'Como é operar esse caminhão todo dia', 'Ato 5 · Driver Scorecard', `<div class="g g2">${pn('Scorecard · veículo atual × Mercedes-Benz (0 a 5)', R.drvN ? radar(R.drvRows, { size: 300 }) : `<div class="co b">${GAP('scorecard preenchido')}</div>`, R.drvN ? `média ponderada: ${n1(R.drvMB)} × ${n1(R.drvAtual)} · ${R.drvN} critérios` : '')}
  <div style="display:flex;flex-direction:column;gap:10px;min-height:0">${T.drv.citacao ? `<div class="pn"><h3>Nas palavras do motorista</h3><p style="font-size:15px;font-weight:600;line-height:1.35">“${esc(T.drv.citacao)}”</p><p class="note">${esc(T.drv.autorCitacao || 'motorista')} ${ev('med')}</p></div>` : ''}${pn('Se pudesse escolher o caminhão para essa rota', `<div class="co">${T.drv.escolha ? nl(T.drv.escolha) : GAP('resposta do motorista')}</div>${T.drv.comentarios ? `<p style="font-size:10.5px;color:var(--ink2);margin-top:8px">${nl(T.drv.comentarios)}</p>` : ''}<p class="note">Fadiga e segurança afetam retenção e sinistro: benefício declarado, não monetizado no TCO. ${ev('hip')}</p>`)}</div></div>`,
  'Scorecard aplicado pelo instrutor no fim do teste · mesmo motorista nos dois veículos');
 // 13 produtividade
 page(13, `${or(T.op.entregasDia, 'n')} entregas ou viagens por dia, ${or(T.tco.dispMB)}% de disponibilidade prevista e ARLA em ${or(String(te.arlaPct || T.tco.arlaMB).replace('.', ','))}% do diesel`, 'Produtividade e ARLA mudam a conta?', 'Ato 6 · Produtividade', `<div class="kpis k4">${kp('Tempo em movimento', `${or(te.tempoMov)}<small> h/dia</small>`, 'Fleetboard', 't')}${kp('Disponibilidade', `${or(T.tco.dispMB)}%`, `plano de manutenção Mercedes-Benz × ${or(T.base.disp, 'n')}% da frota atual ${ev('proj')}`, 'g')}${kp('ARLA 32', `${or(te.arlaPct || T.tco.arlaMB)}%<small> do diesel</small>`, `${rs2(R.opexMB ? R.opexMB.ar : NaN)}/km · declarado no TCO`, 'b')}${kp('Custo de parada', `${rs(R.valorDiaParado)}<small>/dia</small>`, 'receita perdida por indisponibilidade', 'w')}</div>
  <div class="g g2">${pn('Custo operacional por km · atual × Mercedes-Benz', R.opexAtual && R.opexMB ? `<table><thead><tr><th class="l">Componente</th><th>Atual</th><th>Mercedes-Benz</th><th>Δ</th></tr></thead><tbody>${[['Combustível', 'comb'], ['ARLA 32', 'ar'], ['Manutenção', 'ma'], ['Pneus', 'pn'], ['Indisponibilidade', 'pa']].map(([l, k]) => `<tr><td class="l">${l}</td><td>${rs2(R.opexAtual[k])}</td><td>${rs2(R.opexMB[k])}</td><td class="${R.opexAtual[k] - R.opexMB[k] > 0.001 ? 'pos' : R.opexAtual[k] - R.opexMB[k] < -0.001 ? 'neg' : 'dim'}">${rs2(R.opexAtual[k] - R.opexMB[k])}</td></tr>`).join('')}<tr class="tot"><td class="l">Total por km</td><td>${rs2(R.opexAtual.total)}</td><td>${rs2(R.opexMB.total)}</td><td class="${R.opexDelta > 0 ? 'pos' : 'neg'}">${rs2(R.opexDelta)}</td></tr></tbody></table>` : `<div class="co b">${GAP('baseline e premissas MB')}</div>`, 'sem aquisição, juros e residual: só o que a operação sente')}
  ${pn('Leitura', co('Por mês', R.opexDelta > 0 ? `<b>${rs(R.opexDelta * TT.N(T.op.kmMes))}</b> a menos por caminhão em ${n0(TT.N(T.op.kmMes))} km.` : 'Preencher baseline.', 'g') + co('O ARLA não anula o diesel', R.opexAtual && R.opexMB ? `ARLA custa ${rs2(R.opexMB.ar)}/km no Mercedes-Benz; o diesel economiza ${rs2(R.opexAtual.comb - R.opexMB.comb)}/km.` : '—', ''))}</div>`,
  'Fleetboard · plano de manutenção · cálculo Tecar');
 // 14 TCO
 const tcoRows = real ? [['Preço de aquisição', real.M.preco, real.C.preco, 'cli'], ['Juros do financiamento', real.rm.juros, real.rc.juros, 'cal'], ['Combustível', real.rm.dieselC, real.rc.dieselC, 'med'], ['ARLA 32', real.rm.arlaC, real.rc.arlaC, 'cal'], ['Manutenção', real.rm.manutC, real.rc.manutC, T.base.manut ? 'cli' : 'bm'], ['Pneus', real.rm.pneusC, real.rc.pneusC, 'cli'], ['IPVA', real.rm.ipvaC, real.rc.ipvaC, 'cal'], ['Seguro', real.rm.segC, real.rc.segC, 'cal'], ['Custo de parada', real.rm.indispC, real.rc.indispC, 'proj'], ['(−) Valor residual', -real.rm.residual, -real.rc.residual, 'proj']] : [];
 const dif = real ? [['Preço de aquisição', real.C.preco - real.M.preco], ['Juros', real.rc.juros - real.rm.juros], ['Combustível e ARLA', real.rc.dieselC + real.rc.arlaC - real.rm.dieselC - real.rm.arlaC], ['Manutenção e pneus', real.rc.manutC + real.rc.pneusC - real.rm.manutC - real.rm.pneusC], ['IPVA e seguro', real.rc.ipvaC + real.rc.segC - real.rm.ipvaC - real.rm.segC], ['Custo de parada', real.rc.indispC - real.rm.indispC], ['Valor residual', real.rm.residual - real.rc.residual]] : [];
 const shareComb = real ? (real.rc.dieselC + real.rc.arlaC - real.rm.dieselC - real.rm.arlaC) / Math.max(1, dif.filter(d => d[1] > 0).reduce((s, d) => s + d[1], 0)) : NaN;
 page(14, real ? `TCO de ${rs2(real.rm.tcoKm)}/km contra ${rs2(real.rc.tcoKm)}/km: combustível responde por ${pc(shareComb, 0)} do que o Mercedes-Benz ganha` : 'TCO comparativo: dados pendentes', 'Quanto custa cada quilômetro, de verdade', 'Ato 7 · TCO', 'a', real ? `<div class="kpis k4">${kp(esc(T.vt.modelo || 'Mercedes-Benz') + ' a ' + rs(real.M.preco), rs(real.rm.tco), `${rs2(real.rm.tcoKm)}/km · ${rs(real.rm.tcoMes)}/mês · ${n1(real.M.taxa, 2)}% ${real.M.taxaUnit === 'am' ? 'a.m.' : 'a.a.'}`, 'a')}${kp(esc(T.base.modelo || 'Referência') + ' a ' + rs(real.C.preco), rs(real.rc.tco), `${rs2(real.rc.tcoKm)}/km · ${rs(real.rc.tcoMes)}/mês · ${n1(real.C.taxa, 2)}% ${real.C.taxaUnit === 'am' ? 'a.m.' : 'a.a.'}`, 'w')}${kp('Diferença em ' + real.rm.H + ' meses', rs(Math.abs(real.delta)), `${pc(Math.abs(real.deltaPct))} a favor do ${real.delta < 0 ? 'Mercedes-Benz' : 'veículo de referência'} · ${Math.abs(real.deltaPct) <= 0.01 ? 'empate técnico (±1%)' : 'cenário realista'}`, Math.abs(real.deltaPct) <= 0.01 ? 'w' : real.delta < 0 ? 'g' : 'b')}${kp('Onde o Mercedes ganha', rs(dif.filter(d => d[1] > 0).reduce((s, d) => s + d[1], 0)), `perde ${rs(-dif.filter(d => d[1] < 0).reduce((s, d) => s + d[1], 0))} em ${dif.filter(d => d[1] < 0).map(d => d[0].toLowerCase()).join(', ') || '—'}`, 'g')}</div>
  <div class="g g2">${pn('Onde cada um ganha · diferença em R$ nos ' + real.rm.H + ' meses', diverge(dif.map(d => ({ l: d[0], v: d[1] })), { h: 300 }), 'à direita = vantagem do Mercedes-Benz')}
  ${pn('Componente a componente', `<table><thead><tr><th class="l">Componente</th><th>Mercedes-Benz</th><th>Referência</th><th>Ev.</th></tr></thead><tbody>${tcoRows.map(r => `<tr${r[0].startsWith('(') ? ' class="hi"' : ''}><td class="l">${r[0]}</td><td>${rs(r[1])}</td><td>${rs(r[2])}</td><td>${ev(r[3])}</td></tr>`).join('')}<tr class="tot"><td class="l">TCO</td><td>${rs(real.rm.tco)}</td><td>${rs(real.rc.tco)}</td><td></td></tr></tbody></table>`, `${n0(real.rm.kmTot)} km no horizonte`)}</div>` : `<div class="co b">${GAP('TCO')} Faltam: ${R.gaps.filter(g => /TCO|Preço|Consumo real|Quilometragem|diesel/.test(g.campo)).map(g => esc(g.campo)).join(' · ') || 'dados'}</div>`,
  `Metodologia do simulador de TCO da Tecar · ${real ? real.rm.H : 60} meses · ${n0(TT.N(T.op.kmMes))} km/mês · diesel ${rs2(TT.N(T.base.diesel))}/L`);
 // 15 impacto
 page(15, cons ? `${econTxt(R.econAno.conservador)} por caminhão por ano no cenário conservador; payback ${pbTxt(cons)}; ${rs(Math.abs(R.econAno.conservador * 5))} em 5 anos` : 'Impacto financeiro: depende do TCO', 'Quanto ganho e quando', 'Ato 7 · Impacto financeiro', 'a', cons ? `<div class="g g21">${pn('Custo acumulado · ' + real.rm.H + ' meses (cenário conservador)', lines([cons.rm.cum, cons.rc.cum], { names: [esc(T.vt.modelo || 'Mercedes-Benz'), esc(T.base.modelo || 'Referência')], mark: cons.payback, h: 330 }), 'entrada + parcelas + operação − residual no fim')}
  <div style="display:flex;flex-direction:column;gap:10px">${[['conservador', 'Conservador · vai para a proposta', 'g', `consumo MB ${n1(R.cenKml.conservador, 2)} km/L (pior trecho) · atual +3% · diesel +10% · residual −5 p.p.`], ['realista', 'Realista', 'b', `consumo ponderado ${n1(R.cenKml.realista, 2)} km/L · premissas de referência`], ['otimista', 'Otimista · potencial', 'w', `melhor trecho ${n1(R.cenKml.otimista, 2)} km/L · sempre projeção`]].map(([k, l, c, d]) => `<div class="kp ${c}"><div class="l">${l}</div><div class="v">${R.econAno[k] < 0 ? '−' : ''}${rs(Math.abs(R.econAno[k]))}<small> /ano por caminhão</small></div><div class="d">${rs2(R.econKm[k])}/km · ${rs(R.econAno[k] / 12)}/mês · ${rs(R.econAno[k] * 5)} em 5 anos · payback ${pbTxt(R.cen[k])} · ${d} ${ev('proj')}</div></div>`).join('')}</div></div>` : `<div class="co b">${GAP('TCO')}</div>`,
  'Cenários derivados do teste e dos dados do cliente · o conservador não promete o que não foi medido');
 // 16 sensibilidade
 page(16, R.sens ? (R.baseDelta > 0 ? `A vantagem ${R.sens.every(s => R.baseDelta + s.v > 0) ? 'se mantém em todas as variações testadas' : 'inverte em: ' + R.sens.filter(s => R.baseDelta + s.v <= 0).map(s => s.lbl).join(', ')}` : `No cenário realista o Mercedes-Benz fica ${rs(-R.baseDelta)} atrás; ${R.sens.some(s => R.baseDelta + s.v > 0) ? 'vira a favor com: ' + R.sens.filter(s => R.baseDelta + s.v > 0).map(s => s.lbl).join(', ') : 'nenhuma variação isolada inverte o resultado'}`) : 'Sensibilidade: depende do TCO', 'Em que condição a conclusão deixa de valer', 'Ato 7 · Sensibilidade', R.sens ? `<div class="g g21">${pn('Variação da vantagem do Mercedes-Benz em ' + real.rm.H + ' meses (cenário realista)', diverge(R.sens.map(s => ({ l: s.lbl, v: s.v })), { h: 330 }), `vantagem base: ${rs(R.baseDelta)} · barra = quanto muda com cada premissa`)}
  ${pn('Leitura', co('Onde perde força', R.sens.filter(s => s.v < 0).sort((a, b) => a.v - b.v).slice(0, 3).map(s => `<b>${esc(s.lbl)}</b>: ${rs(s.v)}`).join('<br>') || '—', 'w') + co('Fronteira', `Empate técnico = ±1% do TCO (${rs(Math.abs(real.rc.tco) * 0.01)}). ${R.sens.every(s => R.baseDelta + s.v > 0) ? 'Nenhuma variação isolada inverte o resultado.' : 'As variações listadas no título invertem o resultado.'}`, 'a') + `<p class="note">Cada barra varia uma premissa por vez sobre o cenário realista. ${ev('cal')}</p>`)}</div>` : `<div class="co b">${GAP('TCO')}</div>`,
  'Uma premissa por vez · modelo de TCO Tecar');
 // 17 escala
 page(17, R.escala ? `Em ${TT.N(T.cli.frotaElegivel) || 10} caminhões elegíveis, a substituição ${R.econAno.conservador >= 0 ? 'vale' : 'custa'} ${rs(Math.abs(R.econAno.conservador * (TT.N(T.cli.frotaElegivel) || 10)))} por ano e ${rs(Math.abs(R.econAno.conservador * (TT.N(T.cli.frotaElegivel) || 10) * 5))} em 5 anos` : 'Escala para a frota: depende do TCO', 'Qual é o tamanho da decisão', 'Ato 8 · Escala', 'a', R.escala ? `<div class="g g2">${pn('Economia anual por lote · cenário conservador', hbars(R.escala.map(e => ({ l: e.n + (e.n === 1 ? ' caminhão' : ' caminhões'), v: e.ano, c: e.n === (TT.N(T.cli.frotaElegivel) || 0) ? '#B8432F' : '#111318' })), { fmt: rs, h: 300 }), 'frota elegível em destaque')}
  ${pn('Em 5 anos', `<table><thead><tr><th class="l">Lote</th><th>Por ano</th><th>Em 5 anos</th><th>Realista / ano</th></tr></thead><tbody>${R.escala.map(e => `<tr><td class="l b">${e.n} un</td><td>${rs(e.ano)}</td><td class="b">${rs(e.cinco)}</td><td class="dim">${rs(e.anoR)}</td></tr>`).join('')}</tbody></table>` + co('Elegibilidade', `${or(T.cli.frotaElegivel, 'n')} veículos da frota de ${or(T.cli.frotaTotal, 'n')} na mesma aplicação e em idade de troca. ${T.prop.janela ? 'Janela: ' + esc(T.prop.janela) + '.' : ''}`, 'i'))}</div>` : `<div class="co b">${GAP('TCO')}</div>`,
  'Frota elegível informada pelo cliente · economia do cenário conservador por caminhão');
 // 18 riscos
 const prem = [['Consumo do Mercedes-Benz', R.kmlMB > 0 ? n1(R.kmlMB, 2) + ' km/L' : '—', 'med', 'teste em ' + (R.nTrechos || 0) + ' trechos', 'cenário conservador usa o pior trecho carregado'], ['Consumo da frota atual', R.kml0 > 0 ? n1(R.kml0, 2) + ' km/L' : '—', 'cli', esc(T.base.fonteKml || 'cliente'), 'conservador soma 3% ao informado'], ['Representatividade da rota', isN(R.aderencia) ? pc(R.aderencia, 0) + ' de aderência' : '—', 'cal', 'RDI teste × operação', 'aceite do cliente no anexo'], ['Testado × ofertado', `${R.compatDif.length} diferenças`, 'cli', 'ficha técnica × proposta', R.compatDif.length ? 'impacto declarado na página 6' : 'sem diferenças'], ['Manutenção Mercedes-Benz', T.tco.manutMB ? rs2(TT.N(T.tco.manutMB)) + '/km' : '—', 'bm', 'plano de manutenção', 'sensibilidade +30% na página 16'], ['Residual', T.tco.residualMB ? T.tco.residualMB + '% do preço' : 'por depreciação ' + T.tco.deprecMB + '% a.a.', 'proj', 'referência de usados', 'conservador reduz 5 p.p.'], ['Disponibilidade', `${or(T.tco.dispMB)}% × ${or(T.base.disp)}%`, 'proj', 'plano × histórico do cliente', 'conservador iguala à frota atual']];
 page(18, `${prem.length} premissas sustentam a conclusão: ${prem.filter(p => p[2] === 'med').length} medidas, ${prem.filter(p => p[2] === 'cli').length} do cliente, ${prem.filter(p => p[2] === 'proj' || p[2] === 'bm').length} projeção ou benchmark`, 'Quais são os riscos e o que ainda é hipótese', 'Riscos e premissas', 'w', `<div class="g g21">${pn('Premissas', `<table><thead><tr><th class="l">Premissa</th><th class="l">Valor</th><th class="l">Classe</th><th class="l">Fonte</th><th class="l">Mitigação</th></tr></thead><tbody>${prem.map(p => `<tr><td class="l b">${p[0]}</td><td class="l">${p[1]}</td><td class="l">${ev(p[2])}</td><td class="l">${p[3]}</td><td class="l">${p[4]}</td></tr>`).join('')}</tbody></table>`)}
  ${pn('Dados que ainda faltam', R.gaps.length ? `<table><thead><tr><th class="l">Dado</th><th class="l">Prior.</th></tr></thead><tbody>${R.gaps.slice(0, 9).map(g => `<tr><td class="l">${esc(g.campo)}</td><td class="l"><span class="chip ${g.p === 'P0' ? 'b' : g.p === 'P1' ? 'w' : ''}">${g.p}</span></td></tr>`).join('')}</tbody></table>` : co('Completo', 'Nenhum dado pendente no protocolo.', 'g'), `completude do protocolo: ${R.completude}%`)}</div>`,
  'Nada é apresentado como certo além do que foi medido');
 // 19 proposta
 page(19, `A solução: ${or(T.prop.lote, 'n')} × ${or(T.prop.modelo || T.vo.modelo, 'modelo')}${T.prop.preco ? ' a ' + esc(T.prop.preco) : ''}, ${esc(T.prop.condicao || 'condição a definir')}`, 'O que exatamente está sendo proposto', 'Ato 8 · Proposta', `<div class="g g2">${pn('Condição comercial', `<div class="dl"><dt>Lote</dt><dd>${or(T.prop.lote)} unidades</dd><dt>Modelo</dt><dd>${or(T.prop.modelo || T.vo.modelo)}</dd><dt>Preço</dt><dd>${or(T.prop.preco)}</dd><dt>Financiamento</dt><dd>${or(T.prop.condicao)}</dd><dt>Validade</dt><dd>${or(T.prop.validade)}</dd><dt>Janela de compra</dt><dd>${or(T.prop.janela)}</dd></div>` + co('Base do cenário conservador', cons ? `Esta condição gera ${rs(R.econAno.conservador)} por caminhão por ano.` : 'TCO pendente.', 'g'))}
  ${pn('O que está incluído', `<div class="co i">${T.prop.inclui ? nl(T.prop.inclui) : GAP('itens da solução')}</div><p class="note">Caminhão, financiamento Banco Mercedes-Benz, plano de manutenção, telemetria, treinamento de condução e rede Tecar.</p>`)}</div>`,
  'Proposta comercial Tecar' + (T.cli.vendedor ? ' · ' + esc(T.cli.vendedor) : ''));
 // 20 decisão
 const passos = (T.prop.passos || '').split('\n').filter(Boolean).slice(0, 3);
 page(20, 'Decisão proposta e próximos passos', 'O que fazemos agora', 'Ato 8 · Decisão', 'a', `<div class="stmt">${T.prop.decisao ? nl(T.prop.decisao) : GAP('decisão proposta')}</div>${T.prop.criterio ? co('Critério de sucesso do piloto', nl(T.prop.criterio), 'g') : ''}<div class="steps">${(passos.length ? passos : ['', '', '']).map((p, i) => `<div class="s"><b>Passo ${i + 1}</b><span>${p ? esc(p) : GAP('ação · responsável · data')}</span></div>`).join('')}</div>`,
  'Compromisso reversível: o piloto é medido com o mesmo protocolo');
 // anexo fotos
 const fotos = T.fotos.filter(f => f.tipo !== 'mapa');
 if (fotos.length) page('A1', 'Evidências fotográficas do teste', 'veículo, carga, cabine e operação', 'Anexo', `<div class="photos">${fotos.slice(0, 6).map(f => `<figure><img src="${f.src}"><figcaption>${esc(f.legenda || f.tipo)}</figcaption></figure>`).join('')}</div>`, 'Fotografias reais do teste');
 // anexo dados
 page('A2', 'Trechos, abastecimentos e método', 'nível de leitura de 3 minutos', 'Anexo', `<div class="g g2">${pn('Trechos', `<table><thead><tr><th class="l">Trecho</th><th>km</th><th>t</th><th class="l">Cond.</th><th>km/L</th><th>L</th><th>km/h</th><th>Alt.</th><th>Par.</th><th>Urb.%</th></tr></thead><tbody>${T.trechos.slice(0, 16).map(t => `<tr><td class="l">${esc(t.nome || (t.origem + ' → ' + t.destino))}</td><td>${n0(TT.N(t.km))}</td><td>${n1(TT.N(t.cargaT), 1)}</td><td class="l">${esc(t.cond || '')}</td><td>${n1(TT.N(t.kmlFb), 2)}</td><td>${n0(TT.N(t.litros))}</td><td>${n0(TT.N(t.velMedia))}</td><td>${n0(TT.N(t.ganhoAlt))}</td><td>${n0(TT.N(t.paradas))}</td><td>${n0(TT.N(t.urbano))}</td></tr>`).join('') || `<tr><td class="l" colspan="10">—</td></tr>`}</tbody></table>`)}
  <div style="display:flex;flex-direction:column;gap:10px">${pn('Abastecimentos', `<table><thead><tr><th class="l">Data</th><th>Odômetro</th><th>Litros</th><th class="l">Posto</th><th class="l">Obs.</th></tr></thead><tbody>${T.abast.slice(0, 12).map(a => `<tr><td class="l">${dbr(a.data)}</td><td>${n0(TT.N(a.odometro))}</td><td>${n1(TT.N(a.litros), 1)}</td><td class="l">${esc(a.posto || '')}</td><td class="l">${esc(a.obs || '')}</td></tr>`).join('') || `<tr><td class="l" colspan="5">—</td></tr>`}</tbody></table>`)}${pn('Método', `<p style="font-size:10px;color:var(--ink2);line-height:1.5">Consumo ponderado = 1 ÷ (mix carregado ÷ km/L carregado + mix vazio ÷ km/L vazio). L/100 km = 100 ÷ km/L. TCO = aquisição + juros + combustível + ARLA + manutenção + pneus + IPVA + seguro + custo de parada − residual, mês a mês, com depreciação composta e inflação do diesel. Payback = primeiro mês em que o acumulado do Mercedes-Benz fica abaixo do acumulado da referência. Classes de evidência: Medido (teste), Cliente (frota), Cálculo, Projeção, Hipótese, Benchmark.</p>`)}</div></div>`,
  'Dados brutos e fórmulas · aceite de representatividade: ' + (T.cli.contato ? esc(T.cli.contato) : 'pendente'));
 const data = JSON.stringify(T).replace(/<\/script/gi, '<\\/script');
 return `<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>${esc(emp)} — Truck Test 2.0</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>${CSS}</style></head><body>${P.join('')}<script type="application/json" id="trucktest-data">${data}</script></body></html>`;
}
return { build, esc };
})();
